package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"math/rand"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/prometheus/client_golang/prometheus/push"
)


var (
	counter = prometheus.NewCounter(
		prometheus.CounterOpts{
			Namespace: "prom_sample_app",
			Name:      "counter",
			Help:      "Counter generated by the prom sample app",
		})

	gauge = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "prom_sample_app",
			Name:      "gauge",
			Help:      "Gauge generated by the prom sample app",
		})

	summary = prometheus.NewSummary(
		prometheus.SummaryOpts{
			Namespace: "prom_sample_app",
			Name:      "summary",
			Help:      "Summary generated by the prom sample app",
		})
)

var httpRequestCounter = prometheus.NewCounterVec(prometheus.CounterOpts{
    Name: "http_requests_total",
    Help: "Total number of HTTP requests received",
}, []string{"status", "path", "method"})

// Middleware to count HTTP requests
func prometheusMiddleware(next http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        // Wrap the ResponseWriter to capture the status code
        recorder := &statusRecorder{
            ResponseWriter: w,
            statusCode:     http.StatusOK,
        }

        // Process the request
        next.ServeHTTP(recorder, r)

        method := r.Method
        path := r.URL.Path // Path can be adjusted for aggregation (e.g., `/users/:id` → `/users/{id}`)
        status := strconv.Itoa(recorder.statusCode)

        // Increment the counter
        httpRequestCounter.WithLabelValues(status, path, method).Inc()
    })
}
// Helper to capture HTTP status codes
type statusRecorder struct {
    http.ResponseWriter
    statusCode int
}


func (rec *statusRecorder) WriteHeader(code int) {
    rec.statusCode = code
    rec.ResponseWriter.WriteHeader(code)
}
func main() {
	
	port := flag.String("port", "8080", "Port to run the HTTP server on")
	flag.Parse()
	reg := prometheus.NewRegistry()
	reg.MustRegister(counter)
	reg.MustRegister(gauge)
	reg.MustRegister(summary)
	reg.MustRegister(httpRequestCounter)

	go func() {
		for {
			counter.Add(rand.Float64() * 5)
			gauge.Add(rand.Float64()*15 - 5)
			summary.Observe(rand.Float64() * 10)
			time.Sleep(time.Second)
		}
	}()
	

	handler := promhttp.HandlerFor(reg, promhttp.HandlerOpts{})
	
	mux := http.NewServeMux()
	mux.HandleFunc("/", randomResponse)
	mux.HandleFunc("/e500", error500)
	mux.HandleFunc("/push", pushHandler)
	mux.Handle("/metrics", handler)

	promHandler := prometheusMiddleware(mux)
	log.Println("Starting HTTP server on port", *port)

	// log.Fatalf("received error while serving. %v", http.ListenAndServe(":8090", mux))
	if err := http.ListenAndServe(":"+*port, promHandler); err != nil {
        log.Fatal("Server failed to start:", err)
    }
}

func randomResponse(w http.ResponseWriter, req *http.Request) {
	// log.Println(("invoking root endpoing and returning random response"))
	resp := &http.Response{}
	resp.StatusCode = randomiseResponseCode([]int{200, 203, 500, 501, 502, 503, 504, 505})
	writeResponse(w, resp, "random response from the server")
}

func error500(w http.ResponseWriter, req *http.Request) {
	resp := &http.Response{}
	resp.StatusCode = randomiseResponseCode([]int{500, 501, 502, 503, 504, 505})
	writeResponse(w, resp, "Error ~500")
}

func pushHandler(w http.ResponseWriter, req *http.Request) {
	var body struct {
		PushURL string `json:"push_url"`
	}
	if err := json.NewDecoder(req.Body).Decode(&body); err!=nil {
		log.Println(err)
		http.Error(w, "Invallid request body", http.StatusBadRequest)
		return
	}

	if body.PushURL == "" {
		http.Error(w, "push_url is missing from body", http.StatusBadRequest)
		return
	}
	pushReg := prometheus.NewRegistry()
	metric := promauto.With(pushReg).NewGauge(
		prometheus.GaugeOpts{
			Name: "my_sample_push_last_success_seconds",
			Help: "Last successful push",
	})
	metric.SetToCurrentTime()

	pusher := push.New(body.PushURL, "push-test").Gatherer(pushReg)
	var err error

	if (req.Method == http.MethodDelete) {
		err = pusher.Delete()
	} else if(req.Method == http.MethodPost)  {
		err = pusher.Push()
	} else {
		log.Fatalf("[error] failed to process the request, check method, allowed POST or DELETE")
	}

	if err != nil {
		log.Fatalf("[error] failed to process the request ")
	}

	writeResponse(w, &http.Response{StatusCode: http.StatusOK}, "Push operation sucessfully performed to url: "+body.PushURL)
}


func randomiseResponseCode(codes []int) int {
	rn := rand.Intn(len(codes))
	i := rn % len(codes)
	return codes[i]
}

func writeResponse(w http.ResponseWriter, resp *http.Response, bodyContent string) {
	resp.Body = io.NopCloser(strings.NewReader(bodyContent))
	w.WriteHeader(resp.StatusCode)
	body, _ := io.ReadAll(resp.Body)
	_, err := w.Write(body)
	if err != nil {
		fmt.Printf("error while sending respone %v", err)
	}

	_ = resp.Body.Close()
}
