package main

import (
	"crypto/tls"
	"encoding/json"
	"flag"
	"io"
	"math/rand"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/prometheus/client_golang/prometheus/push"
	"github.com/rs/zerolog"
)


var (
	counter = prometheus.NewCounter(
		prometheus.CounterOpts{
			Namespace: "prom_sample_app",
			Name:      "counter",
			Help:      "Counter generated by the prom sample app",
		})

	gauge = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "prom_sample_app",
			Name:      "gauge",
			Help:      "Gauge generated by the prom sample app",
		})

	summary = prometheus.NewSummary(
		prometheus.SummaryOpts{
			Namespace: "prom_sample_app",
			Name:      "summary",
			Help:      "Summary generated by the prom sample app",
		})
)

var httpRequestCounter = prometheus.NewCounterVec(prometheus.CounterOpts{
    Name: "http_requests_total",
    Help: "Total number of HTTP requests received",
}, []string{"status", "path", "method", "testing"})

// Middleware to count HTTP requests
func prometheusMiddleware(next http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        // Wrap the ResponseWriter to capture the status code
        recorder := &statusRecorder{
            ResponseWriter: w,
            statusCode:     http.StatusOK,
        }

        // Process the request
        next.ServeHTTP(recorder, r)

        method := r.Method
        path := r.URL.Path // Path can be adjusted for aggregation (e.g., `/users/:id` → `/users/{id}`)
        status := strconv.Itoa(recorder.statusCode)
		testing := strings.TrimSpace(r.URL.Query().Get("testing"))
		testing = strings.ReplaceAll(testing, "\n", "")
		testing = strings.ReplaceAll(testing, "\r", "")

        // Increment the counter
        httpRequestCounter.WithLabelValues(status, path, method, testing).Inc()
    })
}
// Helper to capture HTTP status codes
type statusRecorder struct {
    http.ResponseWriter
    statusCode int
}

var logger zerolog.Logger
var insecure *bool

func (rec *statusRecorder) WriteHeader(code int) {
    rec.statusCode = code
    rec.ResponseWriter.WriteHeader(code)
}
func main() {
	
	port := flag.String("port", "8080", "Port to run the HTTP server on")
	logLevel := flag.Int("log-level", 1, "Log level for the application: -1:TRACE, 0:DEBUG, 1:INFO, 2:WARN, 3:ERROR, 4:FATA, 5:PANIC")
	insecure = flag.Bool("push-insecure", false, "insecure connection to push endpoint")
	flag.Parse()

	zerolog.SetGlobalLevel(zerolog.Level(*logLevel))
	logger = zerolog.New(os.Stdout).With().Timestamp().Logger()

	reg := prometheus.NewRegistry()
	reg.MustRegister(counter)
	reg.MustRegister(gauge)
	reg.MustRegister(summary)
	reg.MustRegister(httpRequestCounter)

	go func() {
		for {
			counter.Add(rand.Float64() * 5)
			gauge.Add(rand.Float64()*15 - 5)
			summary.Observe(rand.Float64() * 10)
			time.Sleep(time.Second)
		}
	}()
	

	handler := promhttp.HandlerFor(reg, promhttp.HandlerOpts{})
	
	mux := http.NewServeMux()
	mux.HandleFunc("/", randomResponse)
	mux.HandleFunc("/e500", error500)
	mux.HandleFunc("/push", pushHandler)
	mux.Handle("/metrics", handler)

	promHandler := prometheusMiddleware(mux)
	logger.Info().Msgf("Starting HTTP server on port: %s", *port)

	// log.Fatalf("received error while serving. %v", http.ListenAndServe(":8090", mux))
	if err := http.ListenAndServe(":"+*port, promHandler); err != nil {
        logger.Fatal().Msgf("Server failed to start: %v", err)
    }
}

func randomResponse(w http.ResponseWriter, req *http.Request) {
	resp := &http.Response{}
	resp.StatusCode = randomiseResponseCode([]int{200, 203, 204, 205, 206, 207, 401, 403, 404})
	logger.Debug().Int("status", resp.StatusCode).Msg("invoking root endpoint and returning random response")
	writeResponse(w, resp, "random response from the server")
}

func error500(w http.ResponseWriter, req *http.Request) {
	resp := &http.Response{}
	resp.StatusCode = randomiseResponseCode([]int{500, 501, 502, 503, 504, 505})
	logger.Debug().Str("testing", req.URL.Query().Get("testing")).Int("status", resp.StatusCode).Msg("invoking e500 endpoint and returning random response")
	writeResponse(w, resp, "Error ~500")
}

func pushHandler(w http.ResponseWriter, req *http.Request) {
	var body struct {
		PushURL string `json:"push_url"`
		Username string `json:"user"`
		Password string `json:"pass"`
	}
	if err := json.NewDecoder(req.Body).Decode(&body); err!=nil {
		logger.Error().Msgf("invalid request body, got error: %v", err)
		logger.Debug().Msgf("body %v", req.Body)
		http.Error(w, "Invallid request body", http.StatusBadRequest)
		return
	}
	logger.Debug().Msgf("invoking push endpoint and sending request to pg: %s", body.PushURL)

	if body.PushURL == "" {
		logger.Error().Msg("push_url is missing from body")
		http.Error(w, "push_url is missing from body", http.StatusBadRequest)
		return
	}
	pushReg := prometheus.NewRegistry()
	var pushHost string;
	parsedURL, err := url.Parse(body.PushURL)
	if err != nil {
		logger.Info().Msgf("unable to parse push url: %s", body.PushURL)
		pushHost = body.PushURL;
	} else {
		pushHost = parsedURL.Host
	}
	metric := promauto.With(pushReg).NewGauge(
		prometheus.GaugeOpts{
			Name: "my_sample_push_last_success_seconds",
			Help: "Last successful push",
			ConstLabels: prometheus.Labels{"pushgateway": pushHost},
	})
	metric.SetToCurrentTime()

	pusher := push.New(body.PushURL, "push-test").Gatherer(pushReg)
	if *insecure {
		pusher = pusher.Client(
			&http.Client{
				Transport: &http.Transport{
					TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		}})
	}
	if body.Username != "" && body.Password != "" {
		pusher.BasicAuth(body.Username, body.Password)
	}
	if (req.Method == http.MethodDelete) {
		logger.Debug().Msg("calling pusher.delete on the request")
		err = pusher.Delete()
	} else if(req.Method == http.MethodPost)  {
		logger.Debug().Msg("calling pusher.push on the request")
		err = pusher.Push()
	} else {
		logger.Error().Msg("failed to process the request, check method, allowed POST or DELETE")
	}

	if err != nil {
		logger.Error().Msgf("failed to process the request with error: %v", err)
		http.Error(w, "failed to process the request with error", http.StatusBadRequest)
		return
	}

	writeResponse(w, &http.Response{StatusCode: http.StatusOK}, "push operation sucessfully performed to url: "+body.PushURL)
	logger.Debug().Msgf("push operation sucessfully performed to url: %s", body.PushURL)
}


func randomiseResponseCode(codes []int) int {
	rn := rand.Intn(len(codes))
	i := rn % len(codes)
	return codes[i]
}

func writeResponse(w http.ResponseWriter, resp *http.Response, bodyContent string) {
	resp.Body = io.NopCloser(strings.NewReader(bodyContent))
	w.WriteHeader(resp.StatusCode)
	body, _ := io.ReadAll(resp.Body)
	_, err := w.Write(body)
	if err != nil {
		logger.Error().Msgf("error while sending respone: %v", err)
	}
	_ = resp.Body.Close()
}
