package main

import (
	"fmt"
	"io"
	"log"
	"math/rand"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)


var (
	counter = prometheus.NewCounter(
		prometheus.CounterOpts{
			Namespace: "prom_sample_app",
			Name:      "counter",
			Help:      "Counter generated by the prom sample app",
		})

	gauge = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Namespace: "prom_sample_app",
			Name:      "gauge",
			Help:      "Gauge generated by the prom sample app",
		})

	summary = prometheus.NewSummary(
		prometheus.SummaryOpts{
			Namespace: "prom_sample_app",
			Name:      "summary",
			Help:      "Summary generated by the prom sample app",
		})
)

var httpRequestCounter = prometheus.NewCounterVec(prometheus.CounterOpts{
    Name: "http_requests_total",
    Help: "Total number of HTTP requests received",
}, []string{"status", "path", "method"})

// Middleware to count HTTP requests
func prometheusMiddleware(next http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        // Wrap the ResponseWriter to capture the status code
        recorder := &statusRecorder{
            ResponseWriter: w,
            statusCode:     http.StatusOK,
        }

        // Process the request
        next.ServeHTTP(recorder, r)

        method := r.Method
        path := r.URL.Path // Path can be adjusted for aggregation (e.g., `/users/:id` → `/users/{id}`)
        status := strconv.Itoa(recorder.statusCode)

        // Increment the counter
        httpRequestCounter.WithLabelValues(status, path, method).Inc()
    })
}
// Helper to capture HTTP status codes
type statusRecorder struct {
    http.ResponseWriter
    statusCode int
}


func (rec *statusRecorder) WriteHeader(code int) {
    rec.statusCode = code
    rec.ResponseWriter.WriteHeader(code)
}
func main() {
	
	reg := prometheus.NewRegistry()
	reg.MustRegister(counter)
	reg.MustRegister(gauge)
	reg.MustRegister(summary)
	reg.MustRegister(httpRequestCounter)

	go func() {
		for {
			counter.Add(rand.Float64() * 5)
			gauge.Add(rand.Float64()*15 - 5)
			summary.Observe(rand.Float64() * 10)
			time.Sleep(time.Second)
		}
	}()
	

	handler := promhttp.HandlerFor(reg, promhttp.HandlerOpts{})
	
	mux := http.NewServeMux()
	mux.HandleFunc("/", randomResponse)
	mux.HandleFunc("/e500", error500)
	mux.Handle("/metrics", handler)

	promHandler := prometheusMiddleware(mux)


	port := os.Getenv("PORT")
    if port == "" {
        port = "8080"
    }
	log.Println("Starting HTTP server on port", port)

	// log.Fatalf("received error while serving. %v", http.ListenAndServe(":8090", mux))
	if err := http.ListenAndServe(":"+port, promHandler); err != nil {
        log.Fatal("Server failed to start:", err)
    }
}

func randomResponse(w http.ResponseWriter, req *http.Request) {

	resp := randomiseResponseCode(&http.Response{})
	resp.Body = io.NopCloser(strings.NewReader("random response from the server"))

	w.WriteHeader(resp.StatusCode)
	body, _ := io.ReadAll(resp.Body)
	_, err := w.Write(body)
	if err != nil {
		fmt.Printf("error while sending respone %v", err)
	}

	_ = resp.Body.Close()

}

func error500(w http.ResponseWriter, req *http.Request) {
	resp := randomise500ResponseCode(&http.Response{})
	resp.Body = io.NopCloser(strings.NewReader("Error ~500"))

	log.Printf("response: %v ", resp.StatusCode)
	w.WriteHeader(resp.StatusCode)
	body, _ := io.ReadAll(resp.Body)
	_, err := w.Write(body)
	if err != nil {
		fmt.Printf("error while sending respone %v", err)
	}
	_ = resp.Body.Close()
}

func randomiseResponseCode(resp *http.Response) *http.Response {
	codes := []int{200, 203, 500, 501, 502, 503, 504, 505}
	rn := rand.Intn(len(codes))
	i := rn % len(codes)
	resp.StatusCode = codes[i]

	return resp
}


func randomise500ResponseCode(resp *http.Response) *http.Response {
	codes := []int{500, 501, 502, 503, 504, 505}
	rn := rand.Intn(len(codes))
	i := rn % len(codes)
	resp.StatusCode = codes[i]
	return resp
}
